<a href="https://colab.research.google.com/github/nirala-noir/CROWD-COUNTING-using-neural-network--social-distancing/blob/main/basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''RAMAN KUMAR NIRALA
1806048
ARTIFICIAL-INTELLIGENCE'''

'RAMAN KUMAR NIRALA\n1806048\nARTIFICIAL-INTELLIGENCE'

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#DATASET

In [ ]:
jarvis=pd.read_csv("severity.csv")

In [ ]:
jarvis

a  b  c  d  e  f   g  h  i  j  k  l  m  n  o  p  q  r  s  t  severity
0    1  1  1  1  1  6  11  2  1  1  4  1  1  2  1  1  0  1  1  2         2
1    0  0  1  1  2  1  11  1  1  1  6  0  0  4  1  2  0  3  3  3         1
2    1  0  2  1  1  3  11  2  1  1  6  0  0  4  1  2  0  3  0  1         0
3    1  0  1  1  2  1  11  2  1  1  1  1  1  4  2  2  0  3  1  0         2
4    1  0  1  1  1  0  11  3  0  1  0  1  1  0  0  2  0  0  1  0         1
..  .. .. .. .. .. ..  .. .. .. .. .. .. .. .. .. .. .. .. .. ..       ...
969  1  0  1  0  1  0   1  4  1  1  5  0  0  4  1  2  0  0  5  0         3
970  0  1  0  1  4  3   1  0  0  1  0  2  1  4  2  1  4  3  5  1         3
971  1  1  1  1  3  0   2  1  1  1  1  1  1  4  2  2  1  0  0  3         0
972  1  0  0  1  3  1   2  1  1  1  3  2  1  0  0  2  1  3  0  1         0
973  1  1  0  0  4  5   2  3  0  1  0  1  1  4  0  2  4  4  1  3         2

[974 rows x 21 columns]

In [ ]:
x = jarvis.iloc[:,:-1].values
y = jarvis.iloc[:,-1].values

In [ ]:
x

array([[1, 1, 1, ..., 1, 1, 2],
       [0, 0, 1, ..., 3, 3, 3],
       [1, 0, 2, ..., 3, 0, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 3],
       [1, 0, 0, ..., 3, 0, 1],
       [1, 1, 0, ..., 4, 1, 3]])

In [ ]:
y

array([2, 1, 0, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 3, 3, 3, 3, 2, 3, 2,
       1, 2, 2, 1, 2, 0, 2, 3, 2, 2, 3, 0, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2,
       3, 1, 3, 3, 3, 2, 1, 2, 3, 2, 2, 3, 0, 2, 2, 2, 0, 1, 3, 2, 2, 1,
       0, 2, 2, 0, 0, 0, 3, 3, 3, 2, 3, 3, 2, 3, 3, 0, 2, 0, 0, 2, 2, 2,
       2, 0, 0, 3, 0, 2, 2, 1, 1, 2, 3, 3, 3, 0, 1, 3, 2, 3, 1, 3, 3, 3,
       3, 3, 0, 2, 2, 2, 3, 2, 3, 2, 2, 0, 3, 3, 3, 3, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 1, 3, 2, 2, 3, 0, 2, 3, 0, 2, 2, 0,
       1, 2, 2, 3, 0, 2, 3, 3, 1, 0, 3, 1, 3, 3, 2, 0, 3, 3, 1, 3, 1, 1,
       1, 2, 0, 3, 2, 3, 2, 2, 0, 3, 1, 2, 2, 0, 2, 3, 1, 2, 0, 3, 0, 2,
       2, 3, 1, 3, 2, 1, 2, 3, 1, 3, 3, 3, 0, 3, 0, 3, 1, 2, 3, 3, 3, 3,
       3, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 3, 1, 3, 2, 1, 0,
       0, 1, 0, 0, 0, 2, 2, 2, 2, 3, 1, 0, 2, 0, 3, 2, 0, 1, 3, 0, 3, 1,
       3, 1, 2, 0, 3, 2, 3, 2, 2, 3, 2, 3, 2, 0, 2, 3, 0, 2, 2, 1, 2, 2,
       0, 2, 1, 0, 0, 1, 1, 2, 3, 0, 2, 2, 2, 0, 2,

In [ ]:
#splitting

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state= 1)

In [ ]:
print(x_train)

[[1 0 1 ... 3 1 2]
 [1 1 1 ... 3 1 0]
 [0 0 1 ... 0 1 3]
 ...
 [0 0 0 ... 3 3 2]
 [0 0 1 ... 4 2 2]
 [1 0 1 ... 4 2 0]]


In [ ]:
print(x_test)

[[0 0 0 ... 3 5 2]
 [1 1 0 ... 4 1 1]
 [1 0 1 ... 3 2 2]
 ...
 [0 1 1 ... 3 1 0]
 [1 0 2 ... 3 1 1]
 [1 1 2 ... 3 0 1]]


In [ ]:
#training model using logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#making prediction now 

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
y_pred

array([2, 2, 2, 2, 3, 3, 2, 2, 3, 2, 0, 2, 2, 2, 2, 2, 3, 0, 0, 0, 3, 2,
       0, 3, 3, 2, 0, 3, 0, 3, 2, 0, 2, 1, 0, 3, 3, 2, 2, 2, 3, 2, 2, 0,
       0, 2, 2, 0, 2, 2, 0, 3, 2, 3, 2, 0, 0, 0, 3, 0, 2, 2, 2, 3, 2, 3,
       3, 3, 3, 3, 3, 0, 2, 3, 2, 0, 3, 3, 2, 0, 3, 0, 0, 0, 0, 2, 2, 0,
       0, 2, 2, 3, 2, 0, 2, 2, 2, 2, 3, 2, 2, 3, 0, 0, 0, 2, 3, 0, 3, 0,
       3, 2, 3, 2, 3, 0, 3, 3, 0, 2, 0, 2, 2, 2, 3, 2, 2, 3, 2, 2, 3, 3,
       1, 2, 0, 2, 0, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 3, 0, 3, 2, 0, 2,
       2, 3, 0, 3, 3, 2, 3, 2, 3, 2, 2, 2, 0, 3, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 3, 0, 2, 3, 2, 3, 2, 2, 0, 2, 2, 3, 3, 2, 0, 3, 2, 0])

In [ ]:
#gaining model speed using confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[51  0  0  0]
 [ 0  2 15  7]
 [ 0  0 43 20]
 [ 0  1 29 27]]


0.6307692307692307

In [ ]:
#applying keras library to our model

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [ ]:
def get_model():
  model = Sequential()
  model.add(Dense(40, input_dim=20, activation='relu'))
  model.add(Dense(4, activation='softmax'))
  # Compile model
  model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model

In [ ]:
print(x_train.shape,y_train.shape)

(779, 20) (779,)


In [ ]:
estimator = KerasClassifier(build_fn=get_model, epochs=10, batch_size=5, verbose=0)
kfold = KFold(n_splits=10, shuffle=True)
results = cross_val_score(estimator,x, y, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Baseline: 57.70% (6.51%)


In [ ]:
y_train = y_train.reshape(779,1)

In [ ]:
y_train.shape

(779, 1)